collections:
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

image: /assets/images/pixelated-melon-banner.png
description: "I'm a full stack dev and first year CSE undergrad 👾"
