collections:
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

description: "I'm a full stack dev and first year CSE undergrad 👾"

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      image: /assets/images/pixelated-melon-banner.png
